"""Add unique constraint on oauth provider and id

Revision ID: 35cfa399d989
Revises: 1f647eb0053a
Create Date: 2025-11-12 23:53:53.931957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35cfa399d989'
down_revision = '1f647eb0053a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_oauth_provider_id', 'users', ['oauth_provider', 'oauth_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_oauth_provider_id', 'users', type_='unique')
    # ### end Alembic commands ###
