"""Feedback API Endpoints"""

from datetime import datetime
from typing import Optional
from fastapi import APIRouter, HTTPException, status, Query
from app.schemas.feedback import FeedbackCreate, FeedbackResponse
from app.api.dependencies import CurrentUser, FeedbackRepoDepends
from app.core.models import Feedback, FeedbackStatus

router = APIRouter(tags=["Feedback"])


@router.post("/feedback", response_model=FeedbackResponse, status_code=status.HTTP_201_CREATED)
async def submit_feedback(
    feedback_data: FeedbackCreate,
    current_user: CurrentUser,
    feedback_repo: FeedbackRepoDepends,
) -> FeedbackResponse:
    """
    Submit new feedback or suggestion.

    Authenticated users can submit feedback about bugs, feature requests,
    or general comments about the application.

    Args:
        feedback_data: Feedback content and type
        current_user: Authenticated user
        feedback_repo: Feedback repository dependency

    Returns:
        Created feedback

    Raises:
        HTTPException: If validation fails
    """
    # Create domain model
    feedback = Feedback(
        id="",  # Will be generated by repository
        user_id=current_user.id,
        feedback_type=feedback_data.feedback_type,
        message=feedback_data.message,
        status=FeedbackStatus.NEW,
        created_at=datetime.utcnow(),
    )

    # Save to database
    created_feedback = feedback_repo.create(feedback)

    return FeedbackResponse.model_validate(created_feedback)


@router.get("/feedback", response_model=list[FeedbackResponse])
async def list_feedback(
    current_user: CurrentUser,
    feedback_repo: FeedbackRepoDepends,
    status: Optional[FeedbackStatus] = Query(None, description="Filter by status"),
    limit: int = Query(50, ge=1, le=100, description="Maximum number of results"),
    offset: int = Query(0, ge=0, description="Number of results to skip"),
) -> list[FeedbackResponse]:
    """
    List all feedback submissions (admin only, optional for now).

    This endpoint can be used by administrators to view all feedback.
    For now, it's accessible by all authenticated users but can be
    restricted to admin users in the future.

    Args:
        current_user: Authenticated user
        feedback_repo: Feedback repository dependency
        status: Optional status filter (new, reviewed, resolved)
        limit: Maximum number of results (1-100)
        offset: Pagination offset

    Returns:
        List of feedback
    """
    # TODO: Add admin role check when role-based access control is implemented
    # For now, all authenticated users can view feedback

    feedback_list = feedback_repo.list(
        status=status,
        limit=limit,
        offset=offset,
    )

    return [FeedbackResponse.model_validate(fb) for fb in feedback_list]
